services:
  pgdatabase:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdatabase:/var/lib/postgresql/data
    ports:
      - "5432:5432"


